# Information of a keyFrame
#                                                                                                                                                                                                                                

# Image   
sensor_msgs/Image img
sensor_msgs/Image imgDepth
sensor_msgs/Image imgColor
c2tam_msgs/Measurement[] sMeasurements
float64[] se3CfromW
bool bFixed
float64  dSceneDepthMean
float64  dSceneDepthSigma
c2tam_msgs/RgbdInfo[] rgbd

