# Information of a keyFrame
#                                                                                                                                                                                                                                

# Image   
sensor_msgs/Image img
#c2tam_msgs/VCandidates[] vCandidatesOD
float64[] se3CfromW
bool bFixed
bool bSemantic
float64  dSceneDepthMean
float64  dSceneDepthSigma
c2tam_msgs/VSurf[] vSurfOD
float64[] p2d
float64[] p3d
float64[] tco
string name
float64 depth
c2tam_msgs/RgbdInfo[] rgbd

